### ISSUE TITLE
Open tasks for v1.0.0

### ISSUE THREAD

**Issue by dominiquesydow** [dominiquesydow/dynophores#8]
### `core` infrastructure
- [x] Add `Ligand` class - see #21 
- [x] Use superfeature colors as defined in `dynophore-0.2` output instead of hard-coded feature colors in `definitions`; update plots/nglview accordingly - see #22
- [x] Use `Ligand` as `Dynophore` attribute? If ligand PDB block were part of JSON/PML files, that would be fantastic! #31 

### Plots (static/interactive)
- [x] Interactive plots: Too slow for 20k frames. Optimize.
- [x] Plots: Heatmap: Add x/y labels
- [x] Add slider for frame range (min/max)
- [x] Add % to plot labels / legends
- [x] Use [`matplotlib.pyplot.eventplot`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.eventplot.html) for occurrence plots instead of simple dot plots... - see #23
- [x] Interactive plots: Also select envpartners (depending on superfeature)? > Set minimum percentage cutoff to filter out low-coverage envpartners and superfeatures - see #23
- [x] [TBD] Distance plots: Add distance cutoffs or interaction on/off - see https://github.com/dominiquesydow/dynophores/pull/35
  - ~[Medium] Add marker for feature cutoffs (needs feature definitions added to pml file)~
  - ~[Minor] Or add widget that toggles between "all frames" and "only frames where superfeature occurs"~
  - Distance line plot: Add interaction-relevant distances as dots on-top
  - Distance histogram: Plot interaction-relevant distances only
- [x] [Minor] Add tick to collapse envpartners with same residue/different atoms for one superfeature (e.g. ASP 89) - see https://github.com/dominiquesydow/dynophores/pull/36

### 3D viz
- [x] Feature clouds by superfeature ID? At the moment, pml only contains H-123344123124 IDs - can we add H[1234, 1235, ...] to pml?
- [x] ~Check if dcd file has appropriate number of frames (e.g. 1000 frames)~ > For 20k frames this was not a problem in the Jupyter Notebook
- [x] Add interpolation to `nglview` trajectory > Added `nglview.player.TrajectoryPlayer(view)` to notebooks.
- [x] Add frame index to points in PML?
- [x] [Minor] Add pocket residue side chains: We do not have all pocket residues in PML/JSON output but we can add to each superfeature the environmental partners. #28
- [x] [Major] Temporal resolution of dynophore clouds (use point frame index) - see #32 
  - [x] Color clouds by frame index: What kind of color gradient shall we use? Keep feature color and use sequential colormap? Matplotlib has [colormaps](https://matplotlib.org/stable/tutorials/colors/colormaps.html) but can we use our hex colors as endpoint? HSV color model: https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_rgb_to_hsv.html
  - [x] Select cloud points by frame index range: Add slider that allows to select cloud points for selected frame range only? Do we need this?

### 2D viz
- [x] 2D viz: Add 2D ligand view with highlighted features, as done in [KinFragLib](https://nbviewer.jupyter.org/github/volkamerlab/KinFragLib/blob/master/notebooks/2_4_highlight_fragments_in_ligand.ipynb) - see #17 

### CLI
- [x] Make dcd optional!
- [x] Add `dynoviz demo`

### Package
- [x] Make package conda-installable (help from Jaime)
- [x] Make `raise_keyerror_if_invalid_superfeature_name` private!!

### Documentation
- [x] Add prominent link to tutorials?
- [x] Fix code formatting here: https://dynophores.readthedocs.io/en/latest/installing.html > Decided it is ok to have some words highlighted in a different color.
- [x] [Question] How to save widget images? (Missing on GH and RTD)  #29

**Comment by dominiquesydow** [comment]
Hi @nadja-mansurov, 

The interactive plots are already in-place using `ipywidgets` ([code](https://github.com/dominiquesydow/dynophores/blob/master/dynophores/viz/plot/interactive.py)).
Interactive plots are e.g. used in [this notebook](https://github.com/dominiquesydow/dynophores/blob/master/dynophores/notebooks/dynophore.ipynb).

Unfortunately they not displayed in the website-rendered version, to see them you would need to run the notebook locally.

Here a screenshot:
![image](https://user-images.githubusercontent.com/7207093/111513266-e55ad200-8750-11eb-8fce-06e9bcbfd65b.png)

> I have a question regarding
> > Interactive plots: Also select envpartners (depending on superfeature)?

The idea was to add another widget that allows to select the environmental partners (rows) but they depend on the selected superfeatures and that becomes complex.

Instead, I was wondering if we offer widget for a percentage cutoff ("show only all env partners that appear more often than X% of the frames").

What do you think?

**Comment by dominiquesydow** [comment]
> It looks like, that d3.js library could be imported to the notebook. It might be useful to create an interactive visualization of interaction

The d3.js import option for notebooks is amazing!

Do you think this could help us to add interaction partners to this 2D ligand view?

What I have is
![image](https://user-images.githubusercontent.com/7207093/111514747-50f16f00-8752-11eb-822a-169baa39ffc7.png)
(from [dev notebook](https://github.com/dominiquesydow/dynophores/blob/view-2d/docs/tutorials/explore_view2d.ipynb))

What I would like to add around the ligand are the env partners somehow like here:

![image](https://user-images.githubusercontent.com/7207093/111515026-9ca41880-8752-11eb-9c23-0fc6c35f146a.png)
(from [my master thesis](https://edoc.hu-berlin.de/handle/18452/14919) by hand)

**Comment by nadja-mansurov** [comment]
@dominiquesydow thank you for the quick response!
I guess it is possible to create a visualization like the one from your master thesis (thanks a lot for the link! :) )

I can imagine, that 2D visualization will be a "background" and env partners will be added by d3.
Another way is to create a visualization from scratch using a JSON file and d3.js.

I think I will create a separate branch from view-2d, and as the first step just add d3.js there

**Comment by dominiquesydow** [comment]
All features for a version 1.0.0 are implemented - moved a few more technical issues to #25. Closing this issue.
